=== elvindsouza/tmp/Stolen/a4/problem statement solution/Employee.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="Person">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Employee" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="EmpId" type="xs:string" />
                            <xs:element name="EmpName" type="xs:string" />
                            <xs:element name="Department" type="xs:string" />
                            <xs:element name="Salary" type="xs:string" />
                            <xs:element name="Notes" type="xs:string" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== elvindsouza/tmp/4/Employee.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="Employee.xsl"?>
<Person xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Employee.xsd">
    <Employee>
        <EmpId>1</EmpId>
        <EmpName>Linus Torvalds</EmpName>
        <Department>FOSS Advocate</Department>
        <Salary>70000</Salary>
        <Notes>Excellent employee</Notes>
    </Employee>
    <Employee>
        <EmpId>2</EmpId>
        <EmpName>Louis Rossman</EmpName>
        <Department>Right to Repair Advocate</Department>
        <Salary>20000</Salary>
        <Notes>Very good person</Notes>
    </Employee>
    <Employee>
        <EmpId>2</EmpId>
        <EmpName>Sir Micheal II</EmpName>
        <Department>Computer Engineering Wizard</Department>
        <Salary>70000</Salary>
        <Notes>Very rich employee</Notes>
    </Employee>
    <Employee>
        <EmpId>3</EmpId>
        <EmpName>Jebecky Annabell</EmpName>
        <Department>Funny-Named Ghostly Engineer</Department>
        <Salary>16000</Salary>
        <Notes>Who even is this?</Notes>
    </Employee>
    <Employee>
        <EmpId>4</EmpId>
        <EmpName>John Carmicheal</EmpName>
        <Department>Accounting</Department>
        <Salary>17000</Salary>
        <Notes>He doesn't even show up to work</Notes>
    </Employee>
</Person>
