=== elvindsouza/tmp/Stolen/a4/programming assignment solutions/2/tppc.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="Placement">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Job" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Company_name" type="xs:string" />
                            <xs:element name="technology_work" type="xs:string" />
                            <xs:element name="avg_salary" type="xs:decimal" />
                            <xs:element name="year_of_Startup" type="xs:integer" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== elvindsouza/tmp/Stolen/a4/programming assignment solutions/2/tppc.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="tppc.xsl"?>
<Placement xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="tppc.xsd">
    <Job>
        <Company_name>Tata</Company_name>
        <technology_work>System Design</technology_work>
        <avg_salary>123123.123</avg_salary>
        <year_of_Startup>2019</year_of_Startup>
    </Job>
    <Job>
        <Company_name>Hyundai</Company_name>
        <technology_work>Distributed Systems Design</technology_work>
        <avg_salary>12431234.1234</avg_salary>
        <year_of_Startup>2000</year_of_Startup>
    </Job>
    <Job>
        <Company_name>TCS</Company_name>
        <technology_work>Code Monkey</technology_work>
        <avg_salary>12312.312</avg_salary>
        <year_of_Startup>2009</year_of_Startup>
    </Job>
    <Job>
        <Company_name>MonkeyType</Company_name>
        <technology_work>Front-end Engineer</technology_work>
        <avg_salary>234.45324</avg_salary>
        <year_of_Startup>2009</year_of_Startup>
    </Job>
    <Job>
        <Company_name>YouTube</Company_name>
        <technology_work>Back-end Engineer</technology_work>
        <avg_salary>56748654.1234</avg_salary>
        <year_of_Startup>2000</year_of_Startup>
    </Job>
</Placement>
